[package]
name = "obrc"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
itertools = "0.14.0"
libc = "0.2.177"
rustc_data_structures = "0.1.2"

# [profile.release]
# lto = "fat"

[profile.profiling]
inherits = "release"
debug = true
